---
title: "hw-01"
author: "Siddhant Pujni (s2344216)"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}    
knitr::opts_chunk$set(out.width = "100%")
```


------------------------------------------------------------------------------

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse)
library(lubridate)

edibnb <- read_csv("data/edibnb.csv")
council <- read_csv("data/council_assessments.csv")
```

------------------------------------------------------------------------------


## EXERCISE 1

```{r hw1-ex1}

# Finding variables with missing observations
colnames(edibnb)[colSums(is.na(edibnb)) > 0]

# Finding listing ID with most 100% reviews
edibnb %>%
  filter(review_scores_rating == 100) %>%
  arrange(desc(number_of_reviews)) %>%
  filter(row_number() == 1) %>%
  select(id)
  
```

1. The following variables (coloumns) have a missing NA observation:
price, neighbourhood, bathrooms, bedrooms, beds, and review scores rating.

2. The id of the listing with the most 100% reviews is '860170'

------------------------------------------------------------------------------

## EXERCISE 2

```{r hw1-ex2}

# Finding properties in Old Town for one night stay larger than 100GBP
edibnb %>%    
  filter(neighbourhood == "Old Town" & "price" > 100) %>%
  nrow()

# Filtering for properties in Southside that accommodate more than 4 people 
southside_properties <- edibnb %>%
  filter(neighbourhood == "Southside" & "accommodates" >= 4)

# Calculating min, max, and avg price
min(southside_properties$price, na.rm = TRUE)
max(southside_properties$price, na.rm = TRUE)
mean(southside_properties$price, na.rm = TRUE)

```

1. There is 1,283 properties in Old Town where one night stay price is larger than 100 GBP

2. The values for the minimum, maximum, and mean for a one night stay for a group of four in Southside are:
min: 10 GBP a night,
max: 800 GBP a night, and
mean: 107 GBP a night.

------------------------------------------------------------------------------

## EXERCISE 3

```{r hw1-ex3}

# Frequency table for bathrooms in Newington
edibnb %>%
  filter(neighbourhood == "Newington") %>%
  count(bathrooms)

# Creating new variable for rounded bathroom number
edibnb <- edibnb %>%
  mutate(bathrooms_2 = ceiling(bathrooms))

# Counting how many more bathrooms than bedrooms using new variable
edibnb%>%
  filter(bathrooms_2 > bedrooms) %>%
  nrow()
```


1. Frequency table is shown above
2. There is 963 listings with more bathrooms than bedrooms when using the rounded value for the number of bathrooms. 


------------------------------------------------------------------------------

## EXERCISE 4

```{r hw1-ex4}

# Changing variable from character to date class type
council$assessment_date <- dmy(council$assessment_date)

# Finding Properties assessed in May
council %>%
  filter(month(assessment_date) == 5) %>%
  nrow()

# Joining the two data sets
all_data <- left_join(edibnb, council, by = "id")

# Plotting the Bar Chart  
ggplot(data = all_data, 
       mapping = aes(x = neighbourhood)) +
  geom_bar(fill = "blue") +
  labs(
    title = "Bar Plot of Properties Assessed by the Council",
    x = "Neighbourhood",
    y = "Number of Properties Assessed"
  ) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5))

```

1.There was 296 properties assessed in May by the council.

2. The bar plot suggests that the council prioritises assessing properties in Leith over other neighbourhoods in Edinburgh as they have performed more than 3000 assessments there compared to the next closest being Old Town with half as many assessments at roughly 1500. Moreover, there is a lot of properties that have not been assessed at all (the na bar) with the number being roughly 2500 properties. 

------------------------------------------------------------------------------
